version: '3'

services:
  web:
    build: .
    container_name: my_con
    ports:
      - '80:80'
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongo_db/
    depends_on:
      - mongo_db
    networks:
      - backend
  mongo_db:
    image: mongo:4.4.16
    container_name: "mongo_db"
    ports:
      - '27107:27017'
    environment:
      - MONGO_INITDB_DATABASE=Accessories
    networks:
      - backend
networks:
  backend:
    driver: bridge