version: '3'

services:
  web:
    build: .
    container_name: my_con
    ports:
      - '80:80'
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27107:27017'
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"